### ISSUE TITLE
rake assets:precompile fail after upgrade

### ISSUE THREAD

**Issue by ptzool** [sharetribe/sharetribe#1592]
Hi,

When I updated I would like to regenerate assets but I got thi serror messages:

```
AssetSync: Syncing. 
rake aborted!
Excon::Errors::BadRequest: Expected(200) <=> Actual(400 Bad Request)
excon.error.response
  :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'</Message><Region>eu-west-1</Region><RequestId>87B49007681F6CBB</RequestId><HostId>Obyo4tCmHWS93b9KKVBrCpze2lOe7ut5BEBP9+XpdC3PN9xsKWilmrjf2zAjWaWbV3OXu3jaUHw=</HostId></Error>"
  :headers       => {
    "Connection"          => "close"
    "Content-Type"        => "application/xml"
    "Date"                => "Tue, 08 Dec 2015 21:45:31 GMT"
    "Server"              => "AmazonS3"
    "x-amz-bucket-region" => "eu-west-1"
    "x-amz-id-2"          => "aaaaaaaaaaaaaaaaaaaaaaaxsKWilmrjf2zAjWaWbV3OXu3jaUHw="
    "x-amz-request-id"    => "87B49aaaaaaaaaaaaaaa"
  }
  :local_address => "x.x.x.x"
  :local_port    => 48437
  :reason_phrase => "Bad Request"
  :remote_ip     => "54.231.132.18"
  :status        => 400
  :status_line   => "HTTP/1.1 400 Bad Request\r\n"
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:6:in `response_call'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/connection.rb:256:in `rescue in request'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/connection.rb:204:in `request'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/connection.rb:256:in `rescue in request'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/connection.rb:204:in `request'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/connection.rb:256:in `rescue in request'
/usr/local/rvm/gems/ruby-2.1.2/gems/excon-0.45.4/lib/excon/connection.rb:204:in `request'
/usr/local/rvm/gems/ruby-2.1.2/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:35:in `request'
/usr/local/rvm/gems/ruby-2.1.2/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:7:in `request'
/usr/local/rvm/gems/ruby-2.1.2/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:592:in `_request'
/usr/local/rvm/gems/ruby-2.1.2/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:587:in `request'
/usr/local/rvm/gems/ruby-2.1.2/gems/fog-aws-0.7.6/lib/fog/aws/requests/storage/get_bucket.rb:43:in `get_bucket'
/usr/local/rvm/gems/ruby-2.1.2/gems/fog-aws-0.7.6/lib/fog/aws/models/storage/directories.rb:21:in `get'
/usr/local/rvm/gems/ruby-2.1.2/gems/asset_sync-1.0.0/lib/asset_sync/storage.rb:20:in `bucket'
/usr/local/rvm/gems/ruby-2.1.2/gems/asset_sync-1.0.0/lib/asset_sync/storage.rb:99:in `get_remote_files'
/usr/local/rvm/gems/ruby-2.1.2/gems/asset_sync-1.0.0/lib/asset_sync/storage.rb:211:in `upload_files'
/usr/local/rvm/gems/ruby-2.1.2/gems/asset_sync-1.0.0/lib/asset_sync/storage.rb:233:in `sync'
/usr/local/rvm/gems/ruby-2.1.2/gems/asset_sync-1.0.0/lib/asset_sync/asset_sync.rb:29:in `block in sync'
/usr/local/rvm/gems/ruby-2.1.2/gems/asset_sync-1.0.0/lib/asset_sync/asset_sync.rb:51:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/asset_sync-1.0.0/lib/asset_sync/asset_sync.rb:51:in `with_config'
/usr/local/rvm/gems/ruby-2.1.2/gems/asset_sync-1.0.0/lib/asset_sync/asset_sync.rb:28:in `sync'
/usr/local/rvm/gems/ruby-2.1.2/gems/asset_sync-1.0.0/lib/tasks/asset_sync.rake:5:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/gems/asset_sync-1.0.0/lib/tasks/asset_sync.rake:20:in `block in <top (required)>'
Excon::Errors::BadRequest: Expected(200) <=> Actual(400 Bad Request)
```

**Comment by rap1ds** [comment]
@ptzool Thanks for reporting!

We updated the fog gem a week ago and I strongly suspect that it's the reason for this issue: https://github.com/sharetribe/sharetribe/commit/e7010ac79e7e1a36d7a232b461d2be95d2028012

**Comment by rap1ds** [comment]
We're not using AssetSync anymore so this bug is most probably out-dated.
