### ISSUE TITLE
bundle exec rake db:schema:load - throws error

### ISSUE THREAD

**Issue by ivanproskuryakov** [sharetribe/sharetribe#1651]
```sh
bundle exec rake db:schema:load
```
throws the following
```sh
➜  sharetribe git:(master) ✗ bundle exec rake db:schema:load
rake aborted!
NameError: uninitialized constant Mysql2::Client::SECURE_CONNECTION
/Users/ivan/.rvm/gems/ruby-2.1.2/gems/mysql2-0.3.14/lib/mysql2/client.rb:12:in `<class:Client>'
/Users/ivan/.rvm/gems/ruby-2.1.2/gems/mysql2-0.3.14/lib/mysql2/client.rb:2:in `<module:Mysql2>'
/Users/ivan/.rvm/gems/ruby-2.1.2/gems/mysql2-0.3.14/lib/mysql2/client.rb:1:in `<top (required)>'
/Users/ivan/.rvm/gems/ruby-2.1.2/gems/mysql2-0.3.14/lib/mysql2.rb:10:in `require'
/Users/ivan/.rvm/gems/ruby-2.1.2/gems/mysql2-0.3.14/lib/mysql2.rb:10:in `<top (required)>'
/Users/ivan/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `require'
/Users/ivan/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/ivan/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `each'
/Users/ivan/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `block in require'
/Users/ivan/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `each'
/Users/ivan/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `require'
/Users/ivan/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler.rb:132:in `require'
/Users/ivan/www/sharetribe/config/application.rb:14:in `<top (required)>'
/Users/ivan/www/sharetribe/Rakefile:4:in `require'
/Users/ivan/www/sharetribe/Rakefile:4:in `<top (required)>'
/Users/ivan/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/ivan/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by rap1ds** [comment]
Hi! Thanks for reporting the issue.

Could you please use the issue template? That would help us a lot to understand the issue. Thanks!

https://raw.githubusercontent.com/sharetribe/sharetribe/master/ISSUE_TEMPLATE.md

**Comment by rap1ds** [comment]
Inactive. Closing.
