### ISSUE TITLE
#<ThreadError: deadlock; recursive locking> when running the app on puma 2.15.3

### ISSUE THREAD

**Issue by valdis** [sharetribe/sharetribe#1660]
Hi 

We have deployed sharetribe to a server running:
ubuntu 14.04
ruby 2.1.2p95

Randomly the server goes into deadlock, I assume the cause might be the use of Mutex'es in UUID Tools, but i'm not sure on how it can be resolved.

The following is the output from puma's web-1.log

```
2016-01-20 08:07:12 -0500: Rack app error: #<ThreadError: deadlock; recursive locking>
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-1.4.7/lib/rack/lock.rb:14:in `lock'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-1.4.7/lib/rack/lock.rb:14:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/static.rb:83:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:140:in `forward'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:249:in `fetch'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:189:in `lookup'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:66:in `call!'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:51:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:16:in `_call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:12:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/engine.rb:484:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/application.rb:231:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-1.4.7/lib/rack/deflater.rb:13:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/configuration.rb:79:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:541:in `handle_request'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:388:in `process_client'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:270:in `block in run'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
2016-01-20 08:17:08 -0500: Rack app error: #<ThreadError: deadlock; recursive locking>
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-1.4.7/lib/rack/lock.rb:14:in `lock'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-1.4.7/lib/rack/lock.rb:14:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/static.rb:83:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:140:in `forward'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:249:in `fetch'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:189:in `lookup'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:66:in `call!'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:51:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:16:in `_call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:12:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/engine.rb:484:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/application.rb:231:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-1.4.7/lib/rack/deflater.rb:13:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/configuration.rb:79:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:541:in `handle_request'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:388:in `process_client'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:270:in `block in run'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
2016-01-20 08:56:15 -0500: Rack app error: #<ThreadError: deadlock; recursive locking>
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-1.4.7/lib/rack/lock.rb:14:in `lock'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-1.4.7/lib/rack/lock.rb:14:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/static.rb:83:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:140:in `forward'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:249:in `fetch'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:189:in `lookup'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:66:in `call!'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:51:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:16:in `_call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:12:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/engine.rb:484:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/application.rb:231:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-1.4.7/lib/rack/deflater.rb:13:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/configuration.rb:79:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:541:in `handle_request'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:388:in `process_client'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:270:in `block in run'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
2016-01-20 09:09:41 -0500: Rack app error: #<ThreadError: deadlock; recursive locking>
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-1.4.7/lib/rack/lock.rb:14:in `lock'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-1.4.7/lib/rack/lock.rb:14:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/static.rb:83:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:140:in `forward'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:249:in `fetch'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:189:in `lookup'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:66:in `call!'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-cache-1.5.1/lib/rack/cache/context.rb:51:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:16:in `_call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:12:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/engine.rb:484:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/application.rb:231:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/rack-1.4.7/lib/rack/deflater.rb:13:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/configuration.rb:79:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:541:in `handle_request'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:388:in `process_client'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:270:in `block in run'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `call'
/home/rails/staging/shared/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by rap1ds** [comment]
Hi there!

Thanks for reporting the issue.

Currently we are not able to guarantee thread-safety, so we do not recommend running Sharetribe on a threaded server such as Puma. We are using Phusion Passanger and we recommend using that.
