### ISSUE TITLE
Send email error in development

### ISSUE THREAD

**Issue by priviterag** [sharetribe/sharetribe#1735]
**Sharetribe version:**
bfb405f13a16330704d77c45db934cfe20bf1eae

**Environment:**
OSX 10.11.3 (El Captain)

**Server more:**
development

**Description:**

after a fresh install and configuring to use gmail smtp, I get the following error (delayed job log) on second try (first works fine) when inviting new users:
```
[Worker(host:LEONK-MBP pid:74147)] Job InvitationCreatedJob (id=89) RUNNING
INFO 2016-02-16T15:48:29+0100: [Worker(host:LEONK-MBP pid:74147)] Job InvitationCreatedJob (id=89) RUNNING
[Worker(host:LEONK-MBP pid:74147)] Job InvitationCreatedJob (id=89) FAILED (0 prior attempts) with ArgumentError: A copy of SharetribeLogger has been removed from the module tree but is still active!
ERROR 2016-02-16T15:48:29+0100: [Worker(host:LEONK-MBP pid:74147)] Job InvitationCreatedJob (id=89) FAILED (0 prior attempts) with ArgumentError: A copy of SharetribeLogger has been removed from the module tree but is still active!
DEBUG    (0.2ms)  BEGIN
DEBUG   SQL (0.7ms)  UPDATE `delayed_jobs` SET `last_error` = 'A copy of SharetribeLogger has been removed from the module tree but is still active!\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:479:in `load_missing_constant\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:184:in `const_missing\'\n/Users/peppe/projects/toptal/buywearshare/sharetribe/app/utils/sharetribe_logger.rb:41:in `to_hash\'\n/Users/peppe/projects/toptal/buywearshare/sharetribe/app/utils/sharetribe_logger.rb:16:in `info\'\n/Users/peppe/projects/toptal/buywearshare/sharetribe/config/initializers/delayed_job.rb:8:in `block (2 levels) in <class:DelayedJobLoggerPlugin>\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `call\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `call\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `call\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `block in add\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `call\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/backend/base.rb:97:in `invoke_job\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/worker.rb:224:in `block (2 levels) in run\'\n/Users/peppe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout\'\n/Users/peppe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:101:in `call\'\n/Users/peppe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:101:in `timeout\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/worker.rb:224:in `block in run\'\n/Users/peppe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/worker.rb:223:in `run\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/worker.rb:300:in `block in reserve_and_run_one_job\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `call\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `call\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/worker.rb:300:in `reserve_and_run_one_job\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/worker.rb:207:in `block in work_off\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/worker.rb:206:in `times\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/worker.rb:206:in `work_off\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/worker.rb:169:in `block (4 levels) in start\'\n/Users/peppe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/worker.rb:168:in `block (3 levels) in start\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `call\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `call\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/worker.rb:167:in `block (2 levels) in start\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/worker.rb:166:in `loop\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/worker.rb:166:in `block in start\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/plugins/clear_locks.rb:7:in `call\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `call\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `call\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `call\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `block in add\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `call\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/worker.rb:165:in `start\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/delayed_job-4.1.1/lib/delayed/tasks.rb:9:in `block (2 levels) in <top (required)>\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/task.rb:240:in `call\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/task.rb:235:in `each\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain\'\n/Users/peppe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/application.rb:106:in `each\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/lib/rake/application.rb:75:in `run\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/gems/rake-10.5.0/bin/rake:33:in `<top (required)>\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/bin/rake:23:in `load\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/bin/rake:23:in `<main>\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval\'\n/Users/peppe/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>\'', `attempts` = 1, `run_at` = '2016-02-16 14:48:35', `locked_at` = NULL, `locked_by` = NULL, `updated_at` = '2016-02-16 14:48:29' WHERE `delayed_jobs`.`id` = 89
DEBUG    (0.5ms)  COMMIT
DEBUG   SQL (0.5ms)  UPDATE `delayed_jobs` SET `delayed_jobs`.`locked_at` = '2016-02-16 14:48:29', `delayed_jobs`.`locked_by` = 'host:LEONK-MBP pid:74147' WHERE ((run_at <= '2016-02-16 14:48:29.044690' AND (locked_at IS NULL OR locked_at < '2016-02-16 14:45:29.044711') OR locked_by = 'host:LEONK-MBP pid:74147') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1
[Worker(host:LEONK-MBP pid:74147)] 1 jobs processed at 29.8418 j/s, 1 failed
INFO 2016-02-16T15:48:29+0100: [Worker(host:LEONK-MBP pid:74147)] 1 jobs processed at 29.8418 j/s, 1 failed
```

**Comment by rap1ds** [comment]
@priviterag Thanks for reporting the issue. We've seen this happening a couple of times. I'm not exactly sure why this happens, but apparently it has something to do with the Rails class loading mechanism. This shouldn't happen in production environment where classes are eagerly loaded.

As a quick fix, you can try to change the `config/initialize/delayed_job.rb` line 34 from

```ruby
@logger ||= SharetribeLogger.new(:delayed_job)
```

to fully qualified name

```ruby
@logger ||= ::SharetribeLogger.new(:delayed_job)
```

Does that fix the issue?

**Comment by rap1ds** [comment]
More info: https://github.com/activeadmin/activeadmin/issues/2334

**Comment by rap1ds** [comment]
I'm also seeing this error constantly in my development environment. Super annoying, makes development almost impossible.

Restarting the worker works as a quick fix.

**Comment by priviterag** [comment]
@rap1ds Adding the fully qualified name seems fixing the issue. thanks for your help
