### ISSUE TITLE
Migration Fails

### ISSUE THREAD

**Issue by KazKazar** [sharetribe/sharetribe#2090]
I am trying to install Sharetribe. When I run `rake db:migrate` there are some errors. 

##### Sharetribe Version:
ef17fef

##### Environment:
OSX

##### Server mode:
Development mode

##### Steps To Reproduce:
sharetribe installation
`rake db:migrate`

##### Error#1:
```
INFO Migrating to AddDescriptionToItem (20090219094209)
== 20090219094209 AddDescriptionToItem: migrating =============================
-- add_column(:items, :description, :text, {:default=>""})
DEBUG    (0.5ms)  ALTER TABLE `items` ADD `description` text DEFAULT ''
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: BLOB/TEXT column 'description' can't have a default value: ALTER TABLE `items` ADD `description` text DEFAULT ''/Users/.../.rvm/gems/ruby-2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
```
**file: db/migrate/20090219094209_add_description_to_item.rb**
```
class AddDescriptionToItem < ActiveRecord::Migration
  def self.up
    add_column :items, :description, :text, :default => ""
  end
```

##### Error#2:
```
INFO Migrating to AddColumnLastModifiedToListing (20090225073742)
== 20090225073742 AddColumnLastModifiedToListing: migrating ===================
-- add_column(:listings, :last_modified, :datetime)
DEBUG    (37.7ms)  ALTER TABLE `listings` ADD `last_modified` datetime
   -> 0.0385s
DEBUG   Listing Load (0.3ms)  SELECT  `listings`.* FROM `listings` WHERE `listings`.`id` = NULL LIMIT 1
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Couldn't find Listing with 'id'=all/Users/.../.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
```

**file: db/migrate/20090225073742_add_column_last_modified_to_listing.rb**

```
class AddColumnLastModifiedToListing < ActiveRecord::Migration
  def self.up
    add_column :listings, :last_modified, :date time
    #Listing.find(:all).each { |listing| listing.update_attribute :last_modified, listing.created_at}
  end

  def self.down
    remove_column :listings, :last_modified
  end
end

```

##### Error#3:
```
INFO Migrating to AddSettingsToExistingPeople (20090330072036)
== 20090330072036 AddSettingsToExistingPeople: migrating ======================
DEBUG   Person Load (0.3ms)  SELECT  `people`.* FROM `people` WHERE `people`.`id` = 'all' LIMIT 1
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Couldn't find Person with 'id'=all/Users/.../.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
```
**file: db/migrate/20090330072036_add_settings_to_existing_people.rb**

```
class AddSettingsToExistingPeople < ActiveRecord::Migration
  def self.up
    Person.find(:all).each do |person|
      person.settings = Settings.create
    end  
  end

  def self.down
    Person.find(:all).each do |person| 
      person.settings = nil
    end
  end
end

```

##### Error#4:
```
INFO Migrating to MoveDataFromKassiEventsPeopleToKassiEventParticipation (20090730094216)
== 20090730094216 MoveDataFromKassiEventsPeopleToKassiEventParticipation: migrating 
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

uninitialized constant MoveDataFromKassiEventsPeopleToKassiEventParticipation::KassiEvent/Users/../sharetribe/db/migrate/20090730094216_move_data_from_kassi_events_people_to_kassi_event_participation.rb:3:in `up'
```
**file: db/migrate/20090730094216_move_data_from_kassi_events_people_to_kassi_event_participation.rb**
```
class MoveDataFromKassiEventsPeopleToKassiEventParticipation < ActiveRecord::Migration
  def self.up
    KassiEvent.all.each do |event|
      event.people.each do |person|
        if event.realizer_id == person.id
          role = "provider"
        elsif event.receiver_id == person.id
          role = "requester"
        else  
          role = "none"
        end
        KassiEventParticipation.create(:person_id => person.id, 
                                       :kassi_event_id => event.id, 
                                       :role => role)
      end  
    end
  end

  def self.down
    KassiEventParticipation.all.each do |kep|
      kep.destroy
    end  
  end
end

```

**Comment by rap1ds** [comment]
Hi @KazKazar , thanks for reporting!

When you install Sharetribe for the first time, you should use `rake db:schema:load` instead of `rake db:migrate`. See the [installation instructions](https://github.com/sharetribe/sharetribe#setting-up-the-development-environment) step 9. Later, when you are upgrading Sharetribe to newer version, then you need to use `rake db:migrate`.

**Comment by KazKazar** [comment]
@rap1ds thanks!

**Comment by johnsonyeap** [comment]
@rap1ds , did you have schema.rb file in your workspace before running ```rake db:schema:load```?

#2844
