### ISSUE TITLE
Error: Cannot find module 'process/browser.js'

### ISSUE THREAD

**Issue by buildmydream** [sharetribe/sharetribe#2154]
##### Sharetribe Version: 1936a39664eaa282a8f0aa68edc37c9006eb4e59

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._

##### Environment: Mac OS X El Capitan 10.11.5

_What's your environment? Mac OS X, Heroku, or something else?_

##### Server mode: development

_Are you running in development or production mode?_

##### Description: Despite running all steps mentioned in github sequentially, the step described below results in an error.

_In our own words, briefly describe the issue. Please add enough details, yet be concise._

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

1. _Step 1_
1. _Step 2_
1. _Step 3_

Expected result: _What was the expected result after running the steps above?_Not sure. No error??

Actual result: _What was the actual result after running the steps above?_ Error. Please see below.

##### Additional information

_Please provide any additional information that helps debugging, e.g. log output or stack trace of the error_
_admin$ foreman start -f Procfile.static

> 20:03:52 rails.1               | started with pid 24886
20:03:52 rails-client-assets.1 | started with pid 24887
20:03:52 rails-server-assets.1 | started with pid 24888
20:03:52 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
20:03:52 rails.1               | app/assets/webpack/server-bundle.js found
20:03:52 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
20:03:52 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
20:03:52 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
20:03:52 rails-server-assets.1 | client/app/routes/routes.js found
20:03:52 rails-client-assets.1 | 
20:03:52 rails-client-assets.1 | > @ build:dev:client /Users/admin/Documents/marketplace/sharetribe/client
20:03:52 rails-client-assets.1 | > webpack -w --config webpack.client.config.js
20:03:52 rails-client-assets.1 | 
20:03:52 rails-server-assets.1 | 
20:03:52 rails-server-assets.1 | > @ build:dev:server /Users/admin/Documents/marketplace/sharetribe/client
20:03:52 rails-server-assets.1 | > webpack -w --config webpack.server.config.js
20:03:52 rails-server-assets.1 | 
20:03:53 rails-server-assets.1 | module.js:442
20:03:53 rails-server-assets.1 |     throw err;
20:03:53 rails-server-assets.1 |     ^
20:03:53 rails-server-assets.1 | 
20:03:53 rails-server-assets.1 | Error: Cannot find module 'process/browser.js'
20:03:53 rails-server-assets.1 |     at Function.Module._resolveFilename (module.js:440:15)
20:03:53 rails-server-assets.1 |     at Function.resolve (internal/module.js:27:19)
20:03:53 rails-server-assets.1 |     at Object.<anonymous> (/Users/admin/Documents/marketplace/sharetribe/client/node_modules/webpack/node_modules/node-libs-browser/index.js:20:32)
20:03:53 rails-server-assets.1 |     at Module._compile (module.js:541:32)
20:03:53 rails-server-assets.1 |     at Object.Module._extensions..js (module.js:550:10)
20:03:53 rails-server-assets.1 |     at Module.load (module.js:458:32)
20:03:53 rails-server-assets.1 |     at tryModuleLoad (module.js:417:12)
20:03:53 rails-server-assets.1 |     at Function.Module._load (module.js:409:3)
20:03:53 rails-server-assets.1 |     at Module.require (module.js:468:17)
20:03:53 rails-server-assets.1 |     at require (internal/module.js:20:19)
20:03:53 rails-server-assets.1 |     at Object.<anonymous> (/Users/admin/Documents/marketplace/sharetribe/client/node_modules/webpack/lib/node/NodeSourcePlugin.js:7:23)
20:03:53 rails-server-assets.1 |     at Module._compile (module.js:541:32)
20:03:53 rails-server-assets.1 |     at Object.Module._extensions..js (module.js:550:10)
20:03:53 rails-server-assets.1 |     at Module.load (module.js:458:32)
20:03:53 rails-server-assets.1 |     at tryModuleLoad (module.js:417:12)
20:03:53 rails-server-assets.1 |     at Function.Module._load (module.js:409:3)
20:03:53 rails-server-assets.1 |     at Module.require (module.js:468:17)
20:03:53 rails-server-assets.1 |     at require (internal/module.js:20:19)
20:03:53 rails-server-assets.1 |     at OptionsApply.WebpackOptionsApply.process (/Users/admin/Documents/marketplace/sharetribe/client/node_modules/webpack/lib/WebpackOptionsApply.js:72:28)
20:03:53 rails-server-assets.1 |     at webpack (/Users/admin/Documents/marketplace/sharetribe/client/node_modules/webpack/lib/webpack.js:22:48)
20:03:53 rails-server-assets.1 |     at processOptions (/Users/admin/Documents/marketplace/sharetribe/client/node_modules/webpack/bin/webpack.js:152:17)
20:03:53 rails-server-assets.1 |     at Object.<anonymous> (/Users/admin/Documents/marketplace/sharetribe/client/node_modules/webpack/bin/webpack.js:192:1)
20:03:53 rails-server-assets.1 |     at Module._compile (module.js:541:32)
20:03:53 rails-server-assets.1 |     at Object.Module._extensions..js (module.js:550:10)
20:03:53 rails-server-assets.1 |     at Module.load (module.js:458:32)
20:03:53 rails-server-assets.1 |     at tryModuleLoad (module.js:417:12)
20:03:53 rails-server-assets.1 |     at Function.Module._load (module.js:409:3)
20:03:53 rails-server-assets.1 |     at Module.runMain (module.js:575:10)
20:03:53 rails-server-assets.1 |     at run (node.js:348:7)
20:03:53 rails-server-assets.1 |     at startup (node.js:140:9)
20:03:53 rails-server-assets.1 | 
20:03:53 rails-server-assets.1 | npm ERR! Darwin 15.5.0
20:03:53 rails-server-assets.1 | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:dev:server"
20:03:53 rails-server-assets.1 | npm ERR! node v6.2.2
20:03:53 rails-server-assets.1 | npm ERR! nam  v3.10.2
20:03:53 rails-server-assets.1 | npm ERR! code LIFECYCLE
20:03:53 rails-server-assets.1 | npm ERR! @ build:dev:server: `webpack -w --config webpack.server.config.js`
20:03:53 rails-server-assets.1 | npm ERR! Exit status 1
20:03:53 rails-server-assets.1 | npm ERR! 
20:03:53 rails-server-assets.1 | npm ERR! Failed at the @ build:dev:server script 'webpack -w --config webpack.server.config.js'.
20:03:53 rails-server-assets.1 | npm ERR! Make sure you have the latest version of node.js and nam installed.
20:03:53 rails-server-assets.1 | npm ERR! If you do, this is most likely a problem with the  package,
20:03:53 rails-server-assets.1 | npm ERR! not with nam itself.
20:03:53 rails-server-assets.1 | npm ERR! Tell the author that this fails on your system:
20:03:53 rails-server-assets.1 | npm ERR!     webpack -w --config webpack.server.config.js
20:03:53 rails-server-assets.1 | npm ERR! You can get information on how to open an issue for this project with:
20:03:53 rails-server-assets.1 | npm ERR!     nam bugs 
20:03:53 rails-server-assets.1 | npm ERR! Or if that isn't available, you can get their info via:
20:03:53 rails-server-assets.1 | npm ERR!     npm owner ls 
20:03:53 rails-server-assets.1 | npm ERR! There is likely additional logging output above.
20:03:53 rails-server-assets.1 | 
20:03:53 rails-server-assets.1 | npm ERR! Please include the following file with any support request:
20:03:53 rails-server-assets.1 | npm ERR!     /Users/admin/Documents/marketplace/sharetribe/client/npm-debug.log
20:03:53 rails-server-assets.1 | exited with code 1
20:03:53 system                | sending SIGTERM to all processes
20:03:53 rails-client-assets.1 | terminated by SIGTERM
20:03:53 rails.1               | terminated by SIGTERM_

**Comment by buildmydream** [comment]
After looking at other issues reported here, the problem seems to be the same as the one described in 'https://github.com/sharetribe/sharetribe/issues/2037'.

Once I ran the webpack build manually using the command below, the problem went away for me:
cd client && npm run build:client && npm run build:server
