### ISSUE TITLE
asset precompile fails on production

### ISSUE THREAD

**Issue by anbublacky** [sharetribe/sharetribe#2437]
##### Sharetribe Version:

3cba89e3da8f1e7c8de667ed258a72ee25472ea7

##### Environment:

Production

##### Server mode:

Production

##### Description:

When i try to run asset precompile in production, it fails. Also please check document you have missed production environment

##### Steps To Reproduce:

 bundle exec rake RAILS_ENV=production assets:precompile

Expected result: Should have precompiled

Actual result:

EPRECATION WARNING: [paperclip] [deprecation] AWS SDK v1 has been deprecated in paperclip 5. Please consider upgrading to AWS 2 before upgrading paperclip. (called from <class:Person> at /home/deploy/sharetribe/releases/20160823101023/app/models/person.rb:163)
cd client && npm run build:client

> @ build:client /home/deploy/sharetribe/releases/20160823101023/client
> webpack --config webpack.client.config.js

/home/deploy/sharetribe/releases/20160823101023/client/webpack.client.config.js:8
const { replacePercentChar } = require('./webpackConfigUtil');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at module.exports (/home/deploy/sharetribe/releases/20160823101023/client/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/home/deploy/sharetribe/releases/20160823101023/client/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:410:26)

##### Additional information

I have different error but for this project posted at https://github.com/sharetribe/sharetribe/issues/2436

**Comment by rap1ds** [comment]
What's your NodeJS version? Version 6.1 is currently required. If your Node version is less than that, please upgrade and try again.

**Comment by rap1ds** [comment]
This seems to be same error as here: https://www.sharetribe.com/community/t/rake-assets-precompile/242 So upgrading Node version should help.

Closing this issue now.
