### ISSUE TITLE
Error installing npm packages

### ISSUE THREAD

**Issue by osnysantos** [sharetribe/sharetribe#2624]
##### Sharetribe Version:
e8f6f811e4828886ea8c8e5fbd6cd436f7c5566a

##### Environment:
Mac OS Sierra

##### Server mode:
Development

##### Description:
I've installed the requirements and then following the steps to setup, at `npm install` I got some errors.

##### Steps To Reproduce:
Follow the setup using my environment.

Expected result: Packages installed

##### Additional information

Here is error I'm getting:

```
~/projects/sharetribe on master [!]=> (default)
 via 💎  ruby-2.3.1
➔ npm install

> @ postinstall /Users/osnysantos/projects/sharetribe
> cd client && npm install


> caniuse-api@1.5.1 postinstall /Users/osnysantos/projects/sharetribe/client/node_modules/caniuse-api
> node generator.js

module.js:327
    throw err;
    ^

Error: Cannot find module './src/common'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/osnysantos/projects/sharetribe/client/node_modules/shelljs/shell.js:9:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

> phantomjs-prebuilt@2.1.12 install /Users/osnysantos/projects/sharetribe/client/node_modules/phantomjs-prebuilt
> node install.js

module.js:327
    throw err;
    ^

Error: Cannot find module './util/assign'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/osnysantos/projects/sharetribe/client/node_modules/fs-extra/lib/index.js:1:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
npm WARN prefer global colorguard@1.2.0 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-sass@3.8.0 install /Users/osnysantos/projects/sharetribe/client/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/osnysantos/projects/sharetribe/client/node_modules/node-sass/vendor/darwin-x64-46/binding.node

> fsevents@1.0.14 install /Users/osnysantos/projects/sharetribe/client/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/osnysantos/projects/sharetribe/client/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@3.8.0 postinstall /Users/osnysantos/projects/sharetribe/client/node_modules/node-sass
> node scripts/build.js

"/Users/osnysantos/projects/sharetribe/client/node_modules/node-sass/vendor/darwin-x64-46/binding.node" exists.
 testing binary.
Binary is fine; exiting.
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! caniuse-api@1.5.1 postinstall: `node generator.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the caniuse-api@1.5.1 postinstall script 'node generator.js'.
npm ERR! This is most likely a problem with the caniuse-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node generator.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs caniuse-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls caniuse-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/osnysantos/projects/sharetribe/client/npm-debug.log

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! @ postinstall: `cd client && npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ postinstall script 'cd client && npm install'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd client && npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/osnysantos/projects/sharetribe/npm-debug.log

```

**Comment by rap1ds** [comment]
```
npm ERR! node v4.5.0
```

Your node version is way too old. Please install node 6.1 and try again.

**Comment by osnysantos** [comment]
Thanks @rap1ds . Worked!
