### ISSUE TITLE
Error while creating marketplace for the first time after the install

### ISSUE THREAD

**Issue by Beelal** [sharetribe/sharetribe#2779]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version: de76854636e5623cc5c529fc95e25959b50d347b

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._

##### Environment:

_What's your environment? Mac OS X

_What's your node version? Run the following commands and copy the result here:_

```
> node -v v6.5.0
> npm -v v3.10.3
```

##### Server mode:

_Are you running in development or production mode?_ development

##### Description:

_In our own words, briefly describe the issue. Please add enough details, yet be concise._

Error while creating new marketplace

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

Entered all required information to create marketplace.

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

1. _Step 1_
1. _Step 2_
1. _Step 3_

Expected result: _What was the expected result after running the steps above?_

marketplace should have been created

Actual result: _What was the actual result after running the steps above?_

Error:

INFO {"method":"GET","path":"/","format":"html","controller":"homepage","action":"index","status":500,"duration":17496.63,"view":0.0,"db":108.93,"params":{},"host":"gochotu.lvh.me","community_id":1,"current_user_id":"4rON2KJsRdAd_cTJ6MOj-w","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2939.0 Safari/537.36","referer":"http://localhost:3000/communities/new?locale=en","forwarded_for":"","request_uuid":"fe54a186-fa14-4dcf-8332-ea6d9c79bcca"}
INFO {"method":"GET","path":"/","format":"html","controller":"homepage","action":"index","status":500,"duration":17496.63,"view":0.0,"db":108.93,"params":{},"host":"gochotu.lvh.me","community_id":1,"current_user_id":"4rON2KJsRdAd_cTJ6MOj-w","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2939.0 Safari/537.36","referer":"http://localhost:3000/communities/new?locale=en","forwarded_for":"","request_uuid":"fe54a186-fa14-4dcf-8332-ea6d9c79bcca"}
DEBUG ** [Airbrake] Notice was not sent due to configuration:
  Environment Monitored? false
  API key set? false
DEBUG ** [Airbrake] Notice was not sent due to configuration:
  Environment Monitored? false
  API key set? false
FATAL
Errno::ENOENT - No such file or directory @ rb_file_s_mtime - app/assets/webpack/server-bundle.js:
  react_on_rails (6.1.1) lib/react_on_rails/server_rendering_pool/exec.rb:15:in `reset_pool_if_server_bundle_was_modified'
  react_on_rails (6.1.1) lib/react_on_rails/server_rendering_pool.rb:21:in `method_missing'
  react_on_rails (6.1.1) app/helpers/react_on_rails_helper.rb:267:in `server_rendered_react_component_html'
  react_on_rails (6.1.1) app/helpers/react_on_rails_helper.rb:112:in `react_component'
  app/views/layouts/application.haml:17:in `block in _app_views_layouts_application_haml__2267015616686592548_70288082503100'
  actionview (4.2.7.1) lib/action_view/helpers/cache_helper.rb:117:in `cache'
  app/helpers/cache_helper.rb:130:in `react_component_cache'
  app/views/layouts/application.haml:16:in `_app_views_layouts_application_haml__2267015616686592548_70288082503100'
  actionview (4.2.7.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.7.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.7.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:46:in `render_template'
  actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:27:in `render'
  actionview (4.2.7.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.7.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.7.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.7.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.7.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.7.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  activesupport (4.2.7.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  app/controllers/homepage_controller.rb:113:in `block in index'
  app/services/result.rb:70:in `on_success'
  app/controllers/homepage_controller.rb:111:in `index'
  actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.7.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.7.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.7.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.7.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.7.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.7.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  lib/jsroutes_middleware.rb:48:in `call'
   () usr/local/lib/ruby/gems/2.3.0/bundler/gems/i18n-js-2ca6d31365bb/lib/i18n/js/middleware.rb:12:in `call'
  lib/rack_middleware/session_context_middleware.rb:15:in `call'
  lib/rack_middleware/marketplace_lookup.rb:33:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  lib/rack_middleware/custom_cookie_renamer.rb:11:in `call'
  activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/headers.rb:16:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  lograge (0.3.6) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:22:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  lib/rack_middleware/enforce_ssl.rb:23:in `call'
  lib/rack_middleware/health_check.rb:12:in `call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
  rack (1.6.4) lib/rack/deflater.rb:35:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

FATAL
Errno::ENOENT - No such file or directory @ rb_file_s_mtime - app/assets/webpack/server-bundle.js:
  react_on_rails (6.1.1) lib/react_on_rails/server_rendering_pool/exec.rb:15:in `reset_pool_if_server_bundle_was_modified'
  react_on_rails (6.1.1) lib/react_on_rails/server_rendering_pool.rb:21:in `method_missing'
  react_on_rails (6.1.1) app/helpers/react_on_rails_helper.rb:267:in `server_rendered_react_component_html'
  react_on_rails (6.1.1) app/helpers/react_on_rails_helper.rb:112:in `react_component'
  app/views/layouts/application.haml:17:in `block in _app_views_layouts_application_haml__2267015616686592548_70288082503100'
  actionview (4.2.7.1) lib/action_view/helpers/cache_helper.rb:117:in `cache'
  app/helpers/cache_helper.rb:130:in `react_component_cache'
  app/views/layouts/application.haml:16:in `_app_views_layouts_application_haml__2267015616686592548_70288082503100'
  actionview (4.2.7.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.7.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.7.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:46:in `render_template'
  actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:27:in `render'
  actionview (4.2.7.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.7.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.7.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.7.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.7.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.7.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  activesupport (4.2.7.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  app/controllers/homepage_controller.rb:113:in `block in index'
  app/services/result.rb:70:in `on_success'
  app/controllers/homepage_controller.rb:111:in `index'
  actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.7.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.7.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.7.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.7.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.7.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.7.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  lib/jsroutes_middleware.rb:48:in `call'
   () usr/local/lib/ruby/gems/2.3.0/bundler/gems/i18n-js-2ca6d31365bb/lib/i18n/js/middleware.rb:12:in `call'
  lib/rack_middleware/session_context_middleware.rb:15:in `call'
  lib/rack_middleware/marketplace_lookup.rb:33:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  lib/rack_middleware/custom_cookie_renamer.rb:11:in `call'
  activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/headers.rb:16:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  lograge (0.3.6) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:22:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  lib/rack_middleware/enforce_ssl.rb:23:in `call'
  lib/rack_middleware/health_check.rb:12:in `call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
  rack (1.6.4) lib/rack/deflater.rb:35:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

##### Additional information

_Please provide any additional information that helps debugging, e.g. log output or stack trace of the please open sonasoft_x_sonaarc.log under drive:\program files (x86)\sonaarc\log x=name of the exchange server) folder and go to the end of the file and check for errors. _

**Comment by Beelal** [comment]
My bad. I figured out that I didn't run npm install.
