### ISSUE TITLE
FATAL  ActionView::Template::Error

### ISSUE THREAD

**Issue by deviprasad97** [sharetribe/sharetribe#2933]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Environment:
Ubuntu 16.04 Amazon EC2

##### Description:

After deploying the server and trying to create first admin getting this error on the terminal:
DEBUG   ListingShape Load (0.2ms)  SELECT `listing_shapes`.* FROM `listing_shapes` WHERE `listing_shapes`.`community_id` = 1
DEBUG   TransactionProcess Load (0.2ms)  SELECT  `transaction_processes`.* FROM `transaction_processes` WHERE `transaction_processes`.`id` = 1  ORDER BY `transaction_processes`.`id` ASC LIMIT 1
DEBUG    (0.1ms)  BEGIN
DEBUG   SQL (0.2ms)  UPDATE `marketplace_setup_steps` SET `paypal` = 1 WHERE `marketplace_setup_steps`.`id` = 1
DEBUG    (2.3ms)  COMMIT
INFO {"method":"GET","path":"/","format":"html","controller":"homepage","action":"index","status":500,"duration":7135.21,"view":0.0,"db":15.48,"params":{},"host":"store-in-my-house.storeinmyhouse.com","community_id":1,"current_user_id":"lB2UfgD08sZWD8IfqMW6JQ","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36","referer":"http://www.storeinmyhouse.com:3000/communities/new?locale=en","forwarded_for":"","request_uuid":"a31ddf39-30a8-4f36-bacc-96a88dc01729"}
INFO {"method":"GET","path":"/","format":"html","controller":"homepage","action":"index","status":500,"duration":7135.21,"view":0.0,"db":15.48,"params":{},"host":"store-in-my-house.storeinmyhouse.com","community_id":1,"current_user_id":"lB2UfgD08sZWD8IfqMW6JQ","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36","referer":"http://www.storeinmyhouse.com:3000/communities/new?locale=en","forwarded_for":"","request_uuid":"a31ddf39-30a8-4f36-bacc-96a88dc01729"}
DEBUG ** [Airbrake] Notice was not sent due to configuration:         
  Environment Monitored? false         
  API key set? false
DEBUG ** [Airbrake] Notice was not sent due to configuration:         
  Environment Monitored? false         
  API key set? false
FATAL 
ActionView::Template::Error (No such file or directory @ rb_file_s_mtime - app/assets/webpack/server-bundle.js):
    16:       - props = onboarding_topbar_props
    17:       - unless props[:next_step] == :all_done
    18:         - react_component_cache(name: "onboarding_topbar", props: props) do
    19:           = react_component("OnboardingTopBar", props: props, prerender: true)
    20: 
    21:     - if FeatureFlagHelper.feature_enabled?(:topbar_v1)
    22:       - if(search_mode != :keyword || @view_type.eql?("map"))
  app/views/layouts/application.haml:19:in `block in _app_views_layouts_application_haml__3336286220308927236_70152393432280'
  app/helpers/cache_helper.rb:130:in `react_component_cache'
  app/views/layouts/application.haml:18:in `_app_views_layouts_application_haml__3336286220308927236_70152393432280'
  app/controllers/homepage_controller.rb:126:in `block in index'
  app/services/result.rb:70:in `on_success'
  app/controllers/homepage_controller.rb:124:in `index'
  lib/jsroutes_middleware.rb:48:in `call'
  lib/rack_middleware/session_context_middleware.rb:15:in `call'
  lib/rack_middleware/marketplace_lookup.rb:33:in `call'
  lib/rack_middleware/custom_cookie_renamer.rb:11:in `call'
  lib/rack_middleware/enforce_ssl.rb:23:in `call'
  lib/rack_middleware/health_check.rb:12:in `call'

FATAL 
ActionView::Template::Error (No such file or directory @ rb_file_s_mtime - app/assets/webpack/server-bundle.js):
    16:       - props = onboarding_topbar_props
    17:       - unless props[:next_step] == :all_done
    18:         - react_component_cache(name: "onboarding_topbar", props: props) do
    19:           = react_component("OnboardingTopBar", props: props, prerender: true)
    20: 
    21:     - if FeatureFlagHelper.feature_enabled?(:topbar_v1)
    22:       - if(search_mode != :keyword || @view_type.eql?("map"))
  app/views/layouts/application.haml:19:in `block in _app_views_layouts_application_haml__3336286220308927236_70152393432280'
  app/helpers/cache_helper.rb:130:in `react_component_cache'
  app/views/layouts/application.haml:18:in `_app_views_layouts_application_haml__3336286220308927236_70152393432280'
  app/controllers/homepage_controller.rb:126:in `block in index'
  app/services/result.rb:70:in `on_success'
  app/controllers/homepage_controller.rb:124:in `index'
  lib/jsroutes_middleware.rb:48:in `call'
  lib/rack_middleware/session_context_middleware.rb:15:in `call'
  lib/rack_middleware/marketplace_lookup.rb:33:in `call'
  lib/rack_middleware/custom_cookie_renamer.rb:11:in `call'
  lib/rack_middleware/enforce_ssl.rb:23:in `call'
  lib/rack_middleware/health_check.rb:12:in `call'

##### Steps To Reproduce:
bundle exec rails server -b 0.0.0.0
and register first admin via webpage

On webpage
![image](https://cloud.githubusercontent.com/assets/9369708/25072910/219adf7c-22a0-11e7-9b82-f4004c05b67b.png)
Node version 6.10.2
Nodejs Version 3.10.10

**Comment by deviprasad97** [comment]
I solved this issue by removing Nodejs and installing Nodejs 6.9.1 through NVM
Here how I did:
curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh -o install_nvm.sh
bash install_nvm.sh
logged out from the terminal and then:
nvm install 6.1.9
DONE
