### ISSUE TITLE
Cannot find 'vendor' bundle in application.js

### ISSUE THREAD

**Issue by LiamElliott** [sharetribe/sharetribe#2986]
My runs fine on heroku, but not in my local environment using C9. When I run rails s and visit my app, I'm getting a filenot found error. I have the latest versions of node and npm. This is the error that I get when visiting the homepage:
```
ActionView::Template::Error (couldn't find file 'vendor-bundle'
  (in /home/ubuntu/workspace/app/assets/javascripts/application.js:13)):
    89: 
    90:     = javascript_include_tag "i18n/#{I18n.locale}"
    91: 
    92:     = javascript_include_tag 'application'
    93: 
    94:     :javascript
    95:       window.ST.jsonTranslations = #{JSONTranslations.get(I18n.locale)}
  app/views/layouts/application.haml:92:in `_app_views_layouts_application_haml__858310664104650926_70190255185740'
  app/controllers/homepage_controller.rb:126:in `block in index'
  app/services/result.rb:70:in `on_success'
  app/controllers/homepage_controller.rb:124:in `index'
  lib/jsroutes_middleware.rb:48:in `call'
  lib/rack_middleware/session_context_middleware.rb:15:in `call'
  lib/rack_middleware/marketplace_lookup.rb:33:in `call'
  lib/rack_middleware/custom_cookie_renamer.rb:11:in `call'
  lib/rack_middleware/enforce_ssl.rb:23:in `call'
  lib/rack_middleware/health_check.rb:12:in `call'
```

Furthermore, I believe this is a node environment issue as I am unable to run `cd client && npm run build:client && npm run build:server`. It fails with this error message:

```
> @ build:client /home/ubuntu/workspace/client
> npm run ensure-node-version && webpack --config webpack.client.config.js


> @ ensure-node-version /home/ubuntu/workspace/client
> check-node-version --package

node: v6.9.5
npm: v3.10.10
module.js:471
    throw err;
    ^

Error: Cannot find module 'postcss-custom-properties'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/workspace/client/webpack.client.base.config.js:7:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.9.5/bin/node" "/home/ubuntu/.nvm/versions/node/v6.9.5/bin/npm" "run" "build:client"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ build:client: `npm run ensure-node-version && webpack --config webpack.client.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build:client script 'npm run ensure-node-version && webpack --config webpack.client.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run ensure-node-version && webpack --config webpack.client.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/client/npm-debug.log
```
That error happens when running this:

`webpack --config webpack.client.config.js`

How can I fix this so that the app works in my development environment?

**Comment by LiamElliott** [comment]
I fixed this by manually running npm install <package> on packages until it there weren't any errors. For some reason, npm is not installing all of the required dependencies in my environment.
