### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by Jackarnd** [sharetribe/sharetribe#2987]
##### Sharetribe Version:

63cf22673ba74fe0ffc3b1f28f21bf8c2d97310f

##### Environment:

Linux aws (EC2 instance) - Ubuntu (so ssh)
```
> node version : v6.11.0
> npm version : 3.10.10

```

##### Description:
Hello everyone !
I'm trying to install sharetribe on my server as explained in the [tutorial](https://github.com/sharetribe/sharetribe) but I get stuck at the `3. Install node modules`, the npm install doesn't work.

If you can help me, thanks in advance !
Here is my complete error log : 
```
ubuntu@ip-*********:~/sharetribe$ npm install

> undefined postinstall /home/ubuntu/sharetribe
> cd client && npm install

npm WARN checkPermissions Missing write access to /home/ubuntu/sharetribe/client/customloaders/customfileloader/node_modules/big.js
npm WARN checkPermissions Missing write access to /home/ubuntu/sharetribe/client/customloaders/customfileloader/node_modules/json5
npm WARN checkPermissions Missing write access to /home/ubuntu/sharetribe/client/customloaders/customfileloader/node_modules/loader-utils
npm WARN checkPermissions Missing write access to /home/ubuntu/sharetribe/client/customloaders/customfileloader/node_modules
npm ERR! path /home/ubuntu/sharetribe/client/customloaders/customfileloader/node_modules/big.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/home/ubuntu/sharetribe/client/customloaders/customfileloader/node_modules/big.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-06-12T09_29_49_697Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 254
npm ERR! undefined postinstall: `cd client && npm install`
npm ERR! Exit status 254
npm ERR!
npm ERR! Failed at the undefined postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-06-12T09_29_49_721Z-debug.log
```
It appears that node_modules folder doesn't exist (`sharetribe/client/customloaders/customfileloader/node_modules/`)

##### Additional information
Here is the sharetribe npm-debug.log : 
```
ubuntu@ip-*************:~/sharetribe$ cat /home/ubuntu/sharetribe/npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/bin/npm', 'install' ]
2 info using npm@5.0.3
3 info using node@v8.0.0
4 verbose npm-session d5e8441db9ebd7d2
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall sharetribe
7 info lifecycle @~preinstall: @
8 silly lifecycle @~preinstall: no script for preinstall, continuing
9 silly install loadCurrentTree
10 silly install readLocalPackageData
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 silly install loadShrinkwrap
14 silly install loadAllDepsIntoIdealTree
15 silly currentTree sharetribe
16 silly idealTree sharetribe
17 silly install generateActionsToTake
18 silly diffTrees action count 0
19 silly decomposeActions action count 0
20 silly install executeActions
21 silly doSerial global-install 0
22 verbose correctMkdir /home/ubuntu/.npm/_locks correctMkdir not in flight; initializing
23 verbose lock using /home/ubuntu/.npm/_locks/staging-09996f038131cf05.lock for /home/ubuntu/sharetribe/node_modules/.staging
24 silly doParallel extract 0
25 silly doReverseSerial remove 0
26 silly doSerial move 0
27 silly doSerial finalize 0
28 silly doParallel refresh-package-json 0
29 silly doParallel preinstall 0
30 silly doSerial build 0
31 silly doSerial global-link 0
32 silly doParallel update-linked 0
33 silly doSerial install 0
34 silly doSerial postinstall 0
35 verbose unlock done using /home/ubuntu/.npm/_locks/staging-09996f038131cf05.lock for /home/ubuntu/sharetribe/node_modules/.staging
36 silly install runPostinstallTopLevelLifecycles
37 silly build sharetribe
38 info linkStuff !invalid#1
39 silly linkStuff !invalid#1 has /home/ubuntu as its parent node_modules
40 verbose linkBins !invalid#1
41 verbose linkMans !invalid#1
42 silly install sharetribe
43 info lifecycle undefined~install: undefined
44 silly lifecycle undefined~install: no script for install, continuing
45 silly postinstall sharetribe
46 info lifecycle undefined~postinstall: undefined
47 verbose lifecycle undefined~postinstall: unsafe-perm in lifecycle true
48 verbose lifecycle undefined~postinstall: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/ubuntu/sharetribe/node_modules/.bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
49 verbose lifecycle undefined~postinstall: CWD: /home/ubuntu/sharetribe
50 silly lifecycle undefined~postinstall: Args: [ '-c', 'cd client && npm install' ]
51 silly lifecycle undefined~postinstall: Returned: code: 254  signal: null
52 info lifecycle undefined~postinstall: Failed to exec postinstall script
53 verbose stack Error: undefined postinstall: `cd client && npm install`
53 verbose stack Exit status 254
53 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
53 verbose stack     at emitTwo (events.js:125:13)
53 verbose stack     at EventEmitter.emit (events.js:213:7)
53 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
53 verbose stack     at emitTwo (events.js:125:13)
53 verbose stack     at ChildProcess.emit (events.js:213:7)
53 verbose stack     at maybeClose (internal/child_process.js:887:16)
53 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
54 verbose cwd /home/ubuntu/sharetribe
55 verbose Linux 4.4.0-1016-aws
56 verbose argv "/usr/local/bin/node" "/usr/bin/npm" "install"
57 verbose node v8.0.0
58 verbose npm  v5.0.3
59 error code ELIFECYCLE
60 error errno 254
61 error undefined postinstall: `cd client && npm install`
61 error Exit status 254
62 error Failed at the undefined postinstall script.
62 error This is probably not a problem with npm. There is likely additional logging output above.
63 verbose exit [ 254, true ]

```

**Comment by Jackarnd** [comment]
Ok the problem came from the fact that the `node_modules` folder was not at the right place
