### ISSUE TITLE
couldn't find file 'vendor-bundle' with type 'application/javascript'

### ISSUE THREAD

**Issue by thiyagarajan** [sharetribe/sharetribe#3335]
##### Sharetribe Version:
ce645f01148609e2c76c1020eb48e8adff3c7dc9

##### Environment:
centos 7.x

```
> node -v

v8.11.2
> npm -v
5.6.0


##### Server mode:
development

##### Description:

getting "FATAL ActionView::Template::Error (couldn't find file 'vendor-bundle' with type 'application/javascript'"

steps to reproduce:

1. clone the sharetribe code
2. follow the installation process
3. try to start server using $ rails s -b 0.0.0.0

http://sharetribe.moorem.com:3000/

complete log

INFO {"method":"GET","path":"/","format":"html","controller":"HomepageController","action":"index","status":500,"duration":1358.85,"view":0.0,"db":55.93,"params":{},"host":"206.189.115.153","community_id":1,"current_user_id":"E852LOnLeh0irYfcXXEYKQ","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36","referer":"","forwarded_for":"","request_uuid":"5989823e-2546-44f6-a34b-8553dbdc7f59"}
FATAL   
FATAL ActionView::Template::Error (couldn't find file 'vendor-bundle' with type 'application/javascript'
Checked in these paths: 
  /home/deploy/sharetribe/app/assets/font-awesome-icons
  /home/deploy/sharetribe/app/assets/images
  /home/deploy/sharetribe/app/assets/javascripts
  /home/deploy/sharetribe/app/assets/stylesheets
  /home/deploy/sharetribe/vendor/assets/javascripts
  /home/deploy/sharetribe/vendor/assets/stylesheets
  /usr/local/rvm/gems/ruby-2.3.4/gems/js-routes-1.3.3/app/assets/javascripts
  /usr/local/rvm/gems/ruby-2.3.4/gems/i18n-js-3.0.0/app/assets/javascripts
  /usr/local/rvm/gems/ruby-2.3.4/bundler/gems/mercury-1a9d4ac5a0a5/app/assets/images
  /usr/local/rvm/gems/ruby-2.3.4/bundler/gems/mercury-1a9d4ac5a0a5/app/assets/javascripts
  /usr/local/rvm/gems/ruby-2.3.4/bundler/gems/mercury-1a9d4ac5a0a5/app/assets/stylesheets
  /usr/local/rvm/gems/ruby-2.3.4/gems/jquery-rails-4.3.1/vendor/assets/javascripts
  /usr/local/rvm/gems/ruby-2.3.4/gems/coffee-rails-4.2.2/lib/assets/javascripts
  /usr/local/rvm/gems/ruby-2.3.4/gems/actioncable-5.1.1/lib/assets/compiled
  /usr/local/rvm/gems/ruby-2.3.4/gems/actionview-5.1.1/lib/assets/compiled
  /home/deploy/sharetribe/app/assets/webfonts
  /home/deploy/sharetribe/vendor/assets/stylesheets
  /home/deploy/sharetribe/app/assets/webpack):
FATAL     30:   - if @current_community.logo?
    31:     - meta_image = @current_community.logo.url(:original)
    32:   - else
    33:     - meta_image = image_path("sharetribe_icon.png")
    34: 
    35: %title= title
    36: %meta{ :property => "og:title", :content => title}
FATAL   
FATAL app/assets/javascripts/application.js:13
app/views/layouts/_marketplace_head.haml:33:in `_app_views_layouts__marketplace_head_haml___3914016066581791815_69824740293280'
app/views/layouts/_head.haml:28:in `_app_views_layouts__head_haml__1975791047006764708_69824628473120'
app/views/layouts/application.haml:1:in `_app_views_layouts_application_haml__4182137385015449133_69824636742740'
app/controllers/homepage_controller.rb:128:in `block in index'
app/services/result.rb:70:in `on_success'
app/controllers/homepage_controller.rb:126:in `index'
lib/jsroutes_middleware.rb:48:in `call'
lib/rack_middleware/session_context_middleware.rb:15:in `call'
lib/rack_middleware/marketplace_lookup.rb:33:in `call'
lib/rack_middleware/custom_cookie_renamer.rb:11:in `call'
lib/rack_middleware/enforce_ssl.rb:23:in `call'
lib/rack_middleware/health_check.rb:12:in `call'
103.61.167.156 - - [26/May/2018:02:37:53 UTC] "GET / HTTP/1.1" 500 20050
- -> /
103.61.167.156 - - [26/May/2018:02:38:00 UTC] "GET /favicon.ico HTTP/1.1" 200 396
http://206.189.115.153:3000/ -> /favicon.ico

**Comment by thomasmalbaux** [comment]
Hi there!

Thanks for reporting.

Did you run `gem install bundler` a second time, just in case?

Unfortunately I'm not able to reproduce, but don't hesitate to discuss this situation with other open-source users in [Sharetribe's Community forum](https://www.sharetribe.com/community/), someone maybe experienced something similar already.

**Comment by ryankopf** [comment]
This is due to webpacker not running yet and generating required files.

You need to run:
`npm install `
without any errors and then
`rails assets:precompile`
