### ISSUE TITLE
It gets terminated for some reason

### ISSUE THREAD

**Issue by GildedHonour** [sharetribe/sharetribe#3352]
```
      $ foreman start -f Procfile.static
      01:42:43 rails.1               | started with pid 14743
      01:42:43 rails-client-assets.1 | started with pid 14744
      01:42:43 rails-server-assets.1 | started with pid 14745
      01:42:43 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
      01:42:43 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
      01:42:43 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
      01:42:43 rails.1               | app/assets/webpack/server-bundle.js found
      01:42:43 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
      01:42:43 rails-server-assets.1 | client/app/routes/routes.js found
      01:42:44 rails-client-assets.1 | 
      01:42:44 rails-client-assets.1 | > @ build:dev:client /home/alex/projects/ruby/myapp123-sharetribe/client
      01:42:44 rails-client-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.client.config.js
      01:42:44 rails-client-assets.1 | 
      01:42:44 rails-server-assets.1 | 
      01:42:44 rails-server-assets.1 | > @ build:dev:server /home/alex/projects/ruby/myapp123-sharetribe/client
      01:42:44 rails-server-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.server.config.js
      01:42:44 rails-server-assets.1 | 
      01:42:44 rails-client-assets.1 | 
      01:42:44 rails-client-assets.1 | > @ ensure-node-version /home/alex/projects/ruby/myapp123-sharetribe/client
      01:42:44 rails-client-assets.1 | > check-node-version --package
      01:42:44 rails-client-assets.1 | 
      01:42:45 rails-server-assets.1 | 
      01:42:45 rails-server-assets.1 | > @ ensure-node-version /home/alex/projects/ruby/myapp123-sharetribe/client
      01:42:45 rails-server-assets.1 | > check-node-version --package
      01:42:45 rails-server-assets.1 | 
      01:42:45 rails-server-assets.1 | node: v7.8.0
      01:42:45 rails-server-assets.1 | npm: v4.2.0
      01:42:45 rails-client-assets.1 | node: v7.8.0
      01:42:45 rails-client-assets.1 | npm: v4.2.0
      01:42:46 rails-client-assets.1 | Webpack dev build for Rails
      01:42:51 rails.1               | [2018-06-21 01:42:51] INFO  WEBrick 1.4.2
      01:42:51 rails.1               | [2018-06-21 01:42:51] INFO  ruby 2.5.1 (2018-03-29) [x86_64-linux]
      01:42:51 rails.1               | [2018-06-21 01:42:51] INFO  WEBrick::HTTPServer#start: pid=14743 port=5000
      01:42:55 rails-server-assets.1 | Hash: c154c1a0f24b450c17fd
      01:42:55 rails-server-assets.1 | Version: webpack 1.13.3
      01:42:55 rails-server-assets.1 | Time: 9866ms
      01:42:55 rails-server-assets.1 |            Asset     Size  Chunks             Chunk Names
      01:42:55 rails-server-assets.1 | server-bundle.js  4.06 MB       0  [emitted]  main
      01:42:55 rails-server-assets.1 |    [0] multi main 40 bytes {0} [built]
      01:42:55 rails-server-assets.1 |  [650] ./app/i18n/all.js 438 kB {0} [optional] [built]
      01:42:55 rails-server-assets.1 |  [653] ./app/routes/routes.js 155 kB {0} [optional] [built]
      01:42:55 rails-server-assets.1 |     + 1028 hidden modules
      01:43:07 rails-client-assets.1 | terminated by SIGBUS
      01:43:07 system                | sending SIGTERM to all processes
      01:43:07 rails.1               | [2018-06-21 01:43:07] FATAL SignalException: SIGTERM
      01:43:07 rails.1               |        /home/alex/.rubies/ruby-2.5.1/lib/ruby/2.5.0/webrick/server.rb:170:in `select'
      01:43:07 rails.1               |        /home/alex/.rubies/ruby-2.5.1/lib/ruby/2.5.0/webrick/server.rb:170:in `block in start'
      01:43:07 rails.1               |        /home/alex/.rubies/ruby-2.5.1/lib/ruby/2.5.0/webrick/server.rb:32:in `start'
      01:43:07 rails.1               |        /home/alex/.rubies/ruby-2.5.1/lib/ruby/2.5.0/webrick/server.rb:157:in `start'
      01:43:07 rails.1               |        /home/alex/.gem/ruby/2.5.1/gems/rack-2.0.5/lib/rack/handler/webrick.rb:34:in `run'
      01:43:07 rails.1               |        /home/alex/.gem/ruby/2.5.1/gems/rack-2.0.5/lib/rack/server.rb:297:in `start'
      01:43:07 rails.1               |        /home/alex/.gem/ruby/2.5.1/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:44:in `start'
      01:43:07 rails.1               |        /home/alex/.gem/ruby/2.5.1/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:131:in `block in perform'
      01:43:07 rails.1               |        /home/alex/.gem/ruby/2.5.1/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:126:in `tap'
      01:43:07 rails.1               |        /home/alex/.gem/ruby/2.5.1/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:126:in `perform'
      01:43:07 rails.1               |        /home/alex/.gem/ruby/2.5.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
      01:43:07 rails.1               |        /home/alex/.gem/ruby/2.5.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
      01:43:07 rails.1               |        /home/alex/.gem/ruby/2.5.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
      01:43:07 rails.1               |        /home/alex/.gem/ruby/2.5.1/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
      01:43:07 rails.1               |        /home/alex/.gem/ruby/2.5.1/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
      01:43:07 rails.1               |        /home/alex/.gem/ruby/2.5.1/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
      01:43:07 rails.1               |        bin/rails:4:in `require'
      01:43:07 rails.1               |        bin/rails:4:in `<main>'
      01:43:07 rails.1               | [2018-06-21 01:43:07] INFO  going to shutdown ...
      01:43:07 rails.1               | [2018-06-21 01:43:07] INFO  WEBrick::HTTPServer#start done.
      01:43:07 rails.1               | => Booting WEBrick
      01:43:07 rails.1               | => Rails 5.1.1 application starting in development on http://0.0.0.0:5000
      01:43:07 rails.1               | => Run `rails server -h` for more startup options
      01:43:07 rails.1               | Exiting
      01:43:07 rails.1               | terminated by SIGTERM
      01:43:07 rails-server-assets.1 | terminated by SIGTERM

```

What could be the cause?

**Comment by GildedHonour** [comment]
Arch Linux x64
When I'm using ruby 2.3.4, the result remains the same.

**Comment by zenikk** [comment]
The error message from nodejs **terminated by SIGBUS**  is rather an unusual one, so maybe some of your binaries in node_modules are corrupted or invalid for your system.

You can try ```npm rebuild node-sass --force``` or even recompile from source
```
cd client/node_modules/node-sass
node scripts/build -f
```

**Comment by zenikk** [comment]
Check the comments in https://github.com/sass/node-sass/issues/1411#issuecomment-270669797

**Comment by GildedHonour** [comment]
I did that and other modifications. It worked but now after reboot it's the opposite: it hangs and won't reach the state "running on localhost..."

![captura de pantalla_2018-06-22_18-07-21](https://user-images.githubusercontent.com/2032888/41774464-110ae004-764a-11e8-92d1-f05b7ac1d858.png)

**Comment by zenikk** [comment]
So, all your errors come from node-sass under Arch Linux, and are not related to Sharetribe code at all.

I'd recommend you to switch, for example to Ubuntu for smoother development experience, or docker containers,  but if you  want to develop on Arch Linux, you have to search for solutions of related issues like https://stackoverflow.com/questions/37324519/node-sass-does-not-yet-support-your-current-environment-linux-64-bit-with-false

**Comment by pcm211** [comment]
increase the RAM
