### ISSUE TITLE
Installation fails with missing hiredis gem

### ISSUE THREAD

**Issue by priyatam** [sharetribe/sharetribe#3439]
##### Sharetribe Version:

7.3.1

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._

958a83718c444055bc24078b6a54abdbcf172c39

##### Environment:

_What's your environment? Mac OS X, Heroku, or something else?_

*Ubuntu 18.x / Digital Ocean*

_What's your node version? Run the following commands and copy the result here:_

```
> node -v
7.8.0
> npm -v
4.2.0
```

##### Server mode:

_Are you running in development or production mode?_

Unable to install.

##### Description:

I'm unable to install Sharetribe from source as `bundle install` fails with the following:

```
An error occurred while installing hiredis (0.6.1), and Bundler cannot continue.
Make sure that `gem install hiredis -v '0.6.1' --source 'http://rubygems.org/'` succeeds before bundling.
```

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

bundle install

Expected result: all gems installed successfully

Actual result:  

```
An error occurred while installing hiredis (0.6.1), and Bundler cannot continue.
Make sure that `gem install hiredis -v '0.6.1' --source 'http://rubygems.org/'` succeeds before bundling.
```

##### Additional information

`gem install hiredis` results in:

```
± |tag:latest ?:2 ✗| → gem install hiredis
Building native extensions. This could take a while...
ERROR:  Error installing hiredis:
	ERROR: Failed to build gem native extension.

    current directory: /home/neo/.rvm/gems/ruby-2.3.4/gems/hiredis-0.6.1/ext/hiredis_ext
/home/neo/.rvm/rubies/ruby-2.3.4/bin/ruby -r ./siteconf20180922-26338-19j5d0v.rb extconf.rb
checking for sys/socket.h... yes
cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings t  net.c
cc: error: t: No such file or directory
Makefile:136: recipe for target 'net.o' failed
make: *** [net.o] Error 1
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/neo/.rvm/rubies/ruby-2.3.4/bin/$(RUBY_BASE_NAME)
extconf.rb:33:in `block in <main>': Building hiredis failed (RuntimeError)
	from extconf.rb:31:in `chdir'
	from extconf.rb:31:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/neo/.rvm/gems/ruby-2.3.4/extensions/x86_64-linux/2.3.0/hiredis-0.6.1/mkmf.log

extconf failed, exit code 1
```

The contents of mkmf.log:

```
"gcc -E -I/home/neo/.rvm/rubies/ruby-2.3.4/include/ruby-2.3.0/x86_64-linux -I/home/neo/.rvm/rubies/ruby-2.3.4/include/ruby-2.3.0/ruby/backward -I/home/neo/.rvm/rubies/ruby-2.3.4/include/ruby-2.3.0 -I.     -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat  -fPIC  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <sys/socket.h>
/* end */
```

Suggestions?

**Comment by thomasmalbaux** [comment]
Thanks for reporting!

Unfortunately I'm not able to reproduce that error as it seems related to the installation of an extension in your specific setup.

Hopefully you'll be able to find more information from the hiredis channels! Maybe you could also ask at https://www.sharetribe.com/community/ if others have experience the same somehow, in their own environment?

Hopefully this helps.
