### ISSUE TITLE
Error in the bg jobs: 'Input/output error @ io_write - <STDERR>'

### ISSUE THREAD

**Issue by GildedHonour** [sharetribe/sharetribe#3522]
We run our version of Sharetribe on a server. And the background task:

    RAILS_ENV=production nohup bundle exec rake jobs:work >> log/production_bg_jobs.log 2>&1 &

From time to time we have exceptions like this:

```
        id: 310
        priority: 5
        attempts: 3
        handler: --- !ruby/struct:TransactionConfirmedJob
      conversation_id: 1234
      community_id: 1234

      last_error: Input/output error @ io_write - <STDERR>
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/deprecation/behaviors.rb:19:in `write'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/deprecation/behaviors.rb:19:in `puts'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/deprecation/behaviors.rb:19:in `block in <class:Deprecation>'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/deprecation/reporting.rb:21:in `block (2 levels) in warn'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/deprecation/reporting.rb:21:in `each'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/deprecation/reporting.rb:21:in `block in warn'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/deprecation/reporting.rb:20:in `tap'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/deprecation/reporting.rb:20:in `warn'
      /home/ubuntu/my_sharetribe/lib/method_deprecator.rb:6:in `deprecation_warning'
      /home/ubuntu/my_sharetribe/app/models/person.rb:302:in `name'
      /home/ubuntu/my_sharetribe/app/views/person_mailer/transaction_confirmed.html.haml:9:in `_app_views_person_mailer_transaction_confirmed_html_haml___1946728260640541824_70038000420180'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/template.rb:157:in `block in render'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/template.rb:352:in `instrument_render_template'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/template.rb:155:in `render'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/renderer/template_renderer.rb:50:in `render_template'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/renderer/renderer.rb:23:in `render'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/rendering.rb:103:in `_render_template'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/rendering.rb:83:in `render_to_body'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionpack-5.1.1/lib/abstract_controller/rendering.rb:24:in `render'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:935:in `block in collect_responses_from_templates'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:932:in `each'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:932:in `each'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:932:in `map'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:932:in `collect_responses_from_templates'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:917:in `collect_responses'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:830:in `mail'
      /home/ubuntu/my_sharetribe/app/mailers/person_mailer.rb:363:in `premailer_mail'
      /home/ubuntu/my_sharetribe/app/mailers/person_mailer.rb:53:in `block in transaction_confirmed'
      /home/ubuntu/my_sharetribe/app/utils/mail_utils.rb:25:in `block (2 levels) in with_locale'
      /home/ubuntu/my_sharetribe/app/utils/mail_utils.rb:72:in `set_community'
      /home/ubuntu/my_sharetribe/app/utils/mail_utils.rb:24:in `block in with_locale'
      /home/ubuntu/my_sharetribe/app/utils/mail_utils.rb:52:in `set_locale'
      /home/ubuntu/my_sharetribe/app/utils/mail_utils.rb:23:in `with_locale'
      /home/ubuntu/my_sharetribe/app/mailers/person_mailer.rb:52:in `transaction_confirmed'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionpack-5.1.1/lib/abstract_controller/base.rb:186:in `process_action'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionpack-5.1.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:97:in `run_callbacks'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionpack-5.1.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionpack-5.1.1/lib/abstract_controller/base.rb:124:in `process'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/rescuable.rb:23:in `block in process'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/rescuable.rb:22:in `process'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionview-5.1.1/lib/action_view/rendering.rb:30:in `process'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:609:in `block in process'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
      /home/ubuntu/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:608:in `process'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/message_delivery.rb:105:in `block in processed_mailer'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/message_delivery.rb:104:in `tap'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/message_delivery.rb:104:in `processed_mailer'
      /home/ubuntu/.gem/ruby/2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/message_delivery.rb:95:in `deliver_now'
      /home/ubuntu/my_sharetribe/app/utils/mail_carrier.rb:12:in `deliver_now'
      /home/ubuntu/my_sharetribe/app/jobs/transaction_confirmed_job.rb:16:in `perform'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:81:in `block in invoke_job'
      /home/ubuntu/my_sharetribe/config/initializers/delayed_job.rb:10:in `block (2 levels) in <class:DelayedJobLoggerPlugin>'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
      /home/ubuntu/.gem/ruby/2.3.4/gems/airbrake-6.1.2/lib/airbrake/delayed_job.rb:11:in `block (2 levels) in <class:Airbrake>'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block in add'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block in add'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:78:in `invoke_job'
      /home/ubuntu/.gem/ruby/2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/delayed_job_instrumentation.rb:129:in `block in invoke_job'
      /home/ubuntu/.gem/ruby/2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
      /home/ubuntu/.gem/ruby/2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/delayed_job_instrumentation.rb:128:in `invoke_job'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block (2 levels) in run'
      /home/ubuntu/.rubies/ruby-2.3.4/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
      /home/ubuntu/.rubies/ruby-2.3.4/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block in run'
      /home/ubuntu/.rubies/ruby-2.3.4/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:229:in `run'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:213:in `block in work_off'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `times'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `work_off'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:175:in `block (4 levels) in start'
      /home/ubuntu/.rubies/ruby-2.3.4/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:174:in `block (3 levels) in start'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:173:in `block (2 levels) in start'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `loop'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `block in start'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block in add'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:171:in `start'
      /home/ubuntu/.gem/ruby/2.3.4/gems/delayed_job-4.1.5/lib/delayed/tasks.rb:9:in `block (2 levels) in <top (required)>'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
      /home/ubuntu/.gem/ruby/2.3.4/gems/airbrake-6.1.2/lib/airbrake/rake.rb:19:in `execute'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
      /home/ubuntu/.rubies/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
      /home/ubuntu/.gem/ruby/2.3.4/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
      /home/ubuntu/.gem/ruby/2.3.4/bin/rake:22:in `load'
      /home/ubuntu/.gem/ruby/2.3.4/bin/rake:22:in `<top (required)>'
      /home/ubuntu/.gem/ruby/2.3.4/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:74:in `load'
      /home/ubuntu/.gem/ruby/2.3.4/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
      /home/ubuntu/.gem/ruby/2.3.4/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:28:in `run'
      /home/ubuntu/.gem/ruby/2.3.4/gems/bundler-1.16.2/lib/bundler/cli.rb:424:in `exec'
      /home/ubuntu/.gem/ruby/2.3.4/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/ubuntu/.gem/ruby/2.3.4/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/ubuntu/.gem/ruby/2.3.4/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
      /home/ubuntu/.gem/ruby/2.3.4/gems/bundler-1.16.2/lib/bundler/cli.rb:27:in `dispatch'
      /home/ubuntu/.gem/ruby/2.3.4/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
      /home/ubuntu/.gem/ruby/2.3.4/gems/bundler-1.16.2/lib/bundler/cli.rb:18:in `start'
      /home/ubuntu/.gem/ruby/2.3.4/gems/bundler-1.16.2/exe/bundle:30:in `block in <top (required)>'
      /home/ubuntu/.gem/ruby/2.3.4/gems/bundler-1.16.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
      /home/ubuntu/.gem/ruby/2.3.4/gems/bundler-1.16.2/exe/bundle:22:in `<top (required)>'
      /home/ubuntu/.gem/ruby/2.3.4/bin/bundle:22:in `load'
      /home/ubuntu/.gem/ruby/2.3.4/bin/bundle:22:in `<main>'
          run_at: 2018-11-04 22:46:13
       locked_at: 2018-11-04 22:46:17
       failed_at: 2018-11-04 22:46:17
       locked_by: host:ip-11-22-33-44 pid:6514
      created_at: 2018-11-04 22:45:38
      updated_at: 2018-11-04 22:46:17
           queue: default

```

This occurs not only with `TransactionConfirmedJob`, but with other types too.

The code in `person.rb#302` is the original one

What can be the cause?

**Comment by thomasmalbaux** [comment]
Thanks for reporting! At this point I have no clue on what's wrong, unfortunately.

Don't hesitate to share your specific setup with others at https://www.sharetribe.com/community/. Hopefully someone with a similar experience will share their insights!
