### ISSUE TITLE
Bug on selecting one item

### ISSUE THREAD

**Issue by sr7439** [sharetribe/sharetribe#3528]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Environment: Ubuntu 16.04.5 on a VM (VMware workstation 15 Player) on a windows 10.

no

_What's your node version? Run the following commands and copy the result here:_
Node V7.8.0
NPM V4.2.0

> node -v
> npm -v
```

##### Server mode:

_Are you running in development or production mode?_ Development

##### Description:

On the welcome page, after sign in, when selecting one item it shows the bug report page.

##### Steps To Reproduce:

Sign in with a customer account.
Select on item

Expected result: _What was the expected result after running the steps above?_

Show the item

Actual result: _What was the actual result after running the steps above?_

Bug report page shown
![capture du 2018-12-07 10-45-25](https://user-images.githubusercontent.com/45485046/49640225-4a211100-fa0d-11e8-994d-3a188df9743c.png)


##### Additional information

log in the shell where foreman is started is

10:44:26 rails.1               | FATAL 
10:44:26 rails.1               | ArgumentError - Cannot find transaction process: {:process_id=>3, :community_id=>1}:
10:44:26 rails.1               |   app/presenters/listing_presenter.rb:128:in `block in get_transaction_process'
10:44:26 rails.1               |   app/presenters/listing_presenter.rb:127:in `get_transaction_process'
10:44:26 rails.1               |   app/presenters/listing_presenter.rb:82:in `process'
10:44:26 rails.1               |   memoist (0.16.0) lib/memoist.rb:170:in `process'
10:44:26 rails.1               |   app/controllers/listings_controller.rb:98:in `show'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
10:44:26 rails.1               |   actionpack (5.1.1) lib/abstract_controller/base.rb:186:in `process_action'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
10:44:26 rails.1               |   actionpack (5.1.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
10:44:26 rails.1               |   activesupport (5.1.1) lib/active_support/callbacks.rb:131:in `run_callbacks'
10:44:26 rails.1               |   actionpack (5.1.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
10:44:26 rails.1               |   activesupport (5.1.1) lib/active_support/notifications.rb:166:in `block in instrument'
10:44:26 rails.1               |   activesupport (5.1.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
10:44:26 rails.1               |   activesupport (5.1.1) lib/active_support/notifications.rb:166:in `instrument'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
10:44:26 rails.1               |   activerecord (5.1.1) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
10:44:26 rails.1               |   actionpack (5.1.1) lib/abstract_controller/base.rb:124:in `process'
10:44:26 rails.1               |   actionview (5.1.1) lib/action_view/rendering.rb:30:in `process'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_controller/metal.rb:189:in `dispatch'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_controller/metal.rb:253:in `dispatch'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:31:in `serve'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/journey/router.rb:46:in `block in serve'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `serve'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:832:in `call'
10:44:26 rails.1               |   omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
10:44:26 rails.1               |   omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
10:44:26 rails.1               |   meta_request (0.4.3) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
10:44:26 rails.1               |   meta_request (0.4.3) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
10:44:26 rails.1               |   lib/jsroutes_middleware.rb:48:in `call'
10:44:26 rails.1               |   i18n-js (3.0.0) lib/i18n/js/middleware.rb:14:in `call'
10:44:26 rails.1               |   lib/rack_middleware/session_context_middleware.rb:15:in `call'
10:44:26 rails.1               |   lib/rack_middleware/marketplace_lookup.rb:33:in `call'
10:44:26 rails.1               |   rack (2.0.5) lib/rack/method_override.rb:22:in `call'
10:44:26 rails.1               |   warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
10:44:26 rails.1               |   warden (1.2.7) lib/warden/manager.rb:35:in `call'
10:44:26 rails.1               |   rack (2.0.5) lib/rack/etag.rb:25:in `call'
10:44:26 rails.1               |   rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
10:44:26 rails.1               |   rack (2.0.5) lib/rack/head.rb:12:in `call'
10:44:26 rails.1               |   rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
10:44:26 rails.1               |   rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
10:44:26 rails.1               |   lib/rack_middleware/custom_cookie_renamer.rb:11:in `call'
10:44:26 rails.1               |   activerecord (5.1.1) lib/active_record/migration.rb:556:in `call'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
10:44:26 rails.1               |   activesupport (5.1.1) lib/active_support/callbacks.rb:97:in `run_callbacks'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
10:44:26 rails.1               |   airbrake (6.1.2) lib/airbrake/rack/middleware.rb:52:in `call'
10:44:26 rails.1               |   better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
10:44:26 rails.1               |   better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
10:44:26 rails.1               |   better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
10:44:26 rails.1               |   web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
10:44:26 rails.1               |   web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
10:44:26 rails.1               |   web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
10:44:26 rails.1               |   rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
10:44:26 rails.1               |   meta_request (0.4.3) lib/meta_request/middlewares/headers.rb:16:in `call'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
10:44:26 rails.1               |   lograge (0.5.1) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
10:44:26 rails.1               |   railties (5.1.1) lib/rails/rack/logger.rb:24:in `block in call'
10:44:26 rails.1               |   activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
10:44:26 rails.1               |   activesupport (5.1.1) lib/active_support/tagged_logging.rb:26:in `tagged'
10:44:26 rails.1               |   activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `tagged'
10:44:26 rails.1               |   railties (5.1.1) lib/rails/rack/logger.rb:24:in `call'
10:44:26 rails.1               |   sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
10:44:26 rails.1               |   request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/middleware/request_id.rb:25:in `call'
10:44:26 rails.1               |   rack (2.0.5) lib/rack/method_override.rb:22:in `call'
10:44:26 rails.1               |   rack (2.0.5) lib/rack/runtime.rb:22:in `call'
10:44:26 rails.1               |   activesupport (5.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
10:44:26 rails.1               |   actionpack (5.1.1) lib/action_dispatch/middleware/static.rb:125:in `call'
10:44:26 rails.1               |   rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
10:44:26 rails.1               |   lib/rack_middleware/enforce_ssl.rb:23:in `call'
10:44:26 rails.1               |   lib/rack_middleware/health_check.rb:12:in `call'
10:44:26 rails.1               |   railties (5.1.1) lib/rails/engine.rb:522:in `call'
10:44:26 rails.1               |   railties (5.1.1) lib/rails/railtie.rb:185:in `method_missing'
10:44:26 rails.1               |   rack (2.0.5) lib/rack/deflater.rb:34:in `call'
10:44:26 rails.1               |   rack (2.0.5) lib/rack/handler/webrick.rb:86:in `service'
10:44:26 rails.1               |   /home/sylvain/.rbenv/versions/2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
10:44:26 rails.1               |   /home/sylvain/.rbenv/versions/2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
10:44:26 rails.1               |   /home/sylvain/.rbenv/versions/2.3.4/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
10:44:26 rails.1               | 
10:44:27 rails.1               | 127.0.0.1 - - [07/Dec/2018:10:44:26 CET] "GET /fr/listings/1-baguette-petit-epeautre HTTP/1.1" 500 8839
10:44:27 rails.1               | http://127.0.0.1:5000/ -> /fr/listings/1-baguette-petit-epeautre
10:44:27 rails.1               | 127.0.0.1 - - [07/Dec/2018:10:44:27 CET] "POST /__better_errors/f5c3a1467c0204ef/variables HTTP/1.1" 200 15397
10:44:27 rails.1               | http://127.0.0.1:5000/fr/listings/1-baguette-petit-epeautre -> /__better_errors/f5c3a1467c0204ef/variables
10:44:27 rails.1               | 127.0.0.1 - - [07/Dec/2018:10:44:27 CET] "GET /favicon.ico HTTP/1.1" 304 0
10:44:27 rails.1               | - -> /favicon.ico


_Please provide any additional information that helps debugging, e.g. log output or stack trace of the error_

**Comment by thomasmalbaux** [comment]
Thanks for reporting.

As the error message reports, it seems that your current transaction process is not correct.
That means that for some reason your Order Types are broken, or your listing is using an Order Type that has been deleted.

You should review your configuration in your admin panel (Order Types section) and review that listings are using an Order Types still valid (you can check that via the Rails console or database).

Hopefully this helps.
