### ISSUE TITLE
Image Uploading Failed - Encoding::UndefinedConversionError 

### ISSUE THREAD

**Issue by n3rve** [sharetribe/sharetribe#3579]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Environment:

ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
npm 4.2.0
node 7.8.0
Ubuntu 16.04 LTS

##### Server mode:

Production

##### Description:
I have the same issues described [here](https://github.com/sharetribe/sharetribe/issues/1801). Sharetribe installed with all dependencies. Attempts to upload an image show 'image uploading failed' while this is logged:

```
App 7309 stdout: [paperclip] Trying to link /tmp/RackMultipart20190114-7309-1r8zspx.jpg to /tmp/529bec0a4432a38e00090afe5c99acf620190114-7309-iux1ph.jpg
App 7309 stdout: [paperclip] Trying to link /tmp/529bec0a4432a38e00090afe5c99acf620190114-7309-iux1ph.jpg to /tmp/529bec0a4432a38e00090afe5c99acf620190114-7309-j7xljr.jpg
App 7309 stdout: Command :: file -b --mime '/tmp/529bec0a4432a38e00090afe5c99acf620190114-7309-j7xljr.jpg'
App 7309 stdout: {"method":"POST","path":"/en/listings/1/listing_images/add_from_file","format":"text","controller":"ListingImagesController","action":"add_from_file","status":500,"error":"Encoding::UndefinedConversionError: \"\\xA4\" from ASCII-8BIT to UTF-8","duration":33.41,"view":0.0,"db":8.81,"params":{"Content-Type":"image/jpeg","listing_image":"[FILTERED]","locale":"en","listing_id":"1"},"host":"web.enomy.com","community_id":1,"current_user_id":"gAY69RSPVqnR0IS44DN9qw","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36","referer":"https://web.enomy.com/en/listings/1-breakfast-waffles/edit","forwarded_for":"","request_uuid":"ff152b29-2fc7-4666-9bb8-89e5821e0c1c"}
App 7309 stdout:   
App 7309 stdout: Encoding::UndefinedConversionError ("\xA4" from ASCII-8BIT to UTF-8):
App 7309 stdout:   
App 7309 stdout: lib/sharetribe_logger.rb:26:in `error'
App 7309 stdout: app/controllers/listing_images_controller.rb:107:in `new_image'
App 7309 stdout: app/controllers/listing_images_controller.rb:88:in `add_image'
App 7309 stdout: app/controllers/listing_images_controller.rb:52:in `add_from_file'
App 7309 stdout: lib/rack_middleware/session_context_middleware.rb:15:in `call'
App 7309 stdout: lib/rack_middleware/marketplace_lookup.rb:33:in `call'
App 7309 stdout: lib/rack_middleware/custom_cookie_renamer.rb:11:in `call'
App 7309 stdout: lib/rack_middleware/enforce_ssl.rb:23:in `call'
App 7309 stdout: lib/rack_middleware/health_check.rb:12:in `call'
App 7309 stdout: {"method":"POST","path":"/500","format":"text","controller":"ErrorsController","action":"not_found","status":404,"duration":6.55,"view":1.66,"db":1.01,"params":{"Content-Type":"image/jpeg","listing_image":"[FILTERED]","locale":"en","listing_id":"1","path":"500"},"host":null,"community_id":null,"current_user_id":null,"user_agent":null,"referer":null,"forwarded_for":null,"request_uuid":null}
```

##### Steps To Reproduce:

Install Sharetribe on Ubuntu 16.04 and attempt to upload images for items. 
I've also tried installing the gem **activesupport-json_encoder** as suggested on the linked thread.

**Comment by n3rve** [comment]
Found the issue. I didn't have delayed jobs running. I started a screen session and executed the rake jobs work commands and now I can upload images fine. 
```
apt-get install -y screen && screen 
cd /path/to/sharetribe
RAILS_ENV=production bundle exec rake jobs:work
```
Can anyone suggest a better way to keep the worker running instead of using screen?

**Comment by thomasmalbaux** [comment]
Good to hear that it works now!

Some open-source users have been recommending their solutions to run the jobs in the Community forum at https://www.sharetribe.com/community/

Have a look and don't hesitate to discuss things there!
