### ISSUE TITLE
bundle exec rake db:create db:structure:load

### ISSUE THREAD

**Issue by Sultan91** [sharetribe/sharetribe#3787]
##### Sharetribe Version:

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._
8948491e096f7918c89c8f2066c9e1d467b5d472

##### Environment:

_What's your environment? Mac OS X, Heroku, or something else?
No, local machine Ubuntu 18.10

_What's your node version? Run the following commands and copy the result here:_

```
> node -v
7.8..0
> npm -v
4.2..0
```

##### Server mode:

_Are you running in development or production mode?_
development
##### Description:

_In our own words, briefly describe the issue. Please add enough details, yet be concise._
During installation stage: "7)Create and initialize the database"

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

I was running Setting up the development environment part, all thing were running good untill step 7` Create and initialize the database:
bundle exec rake db:create db:structure:load`

Expected result: No errors i guess

Actual result: 
I got following error: 
`rake aborted!
LoadError: cannot load such file -- arel/visitors/mysql
/home/sula/.rvm/gems/ruby-2.6.2/gems/arel-8.0.0/lib/arel/visitors.rb:7:in `require'
/home/sula/.rvm/gems/ruby-2.6.2/gems/arel-8.0.0/lib/arel/visitors.rb:7:in `<top (required)>'
/home/sula/.rvm/gems/ruby-2.6.2/gems/arel-8.0.0/lib/arel.rb:17:in `require'
/home/sula/.rvm/gems/ruby-2.6.2/gems/arel-8.0.0/lib/arel.rb:17:in `<top (required)>'
/home/sula/.rvm/gems/ruby-2.6.2/gems/activerecord-5.1.6.2/lib/active_record.rb:27:in `require'
/home/sula/.rvm/gems/ruby-2.6.2/gems/activerecord-5.1.6.2/lib/active_record.rb:27:in `<top (required)>'
/home/sula/.rvm/gems/ruby-2.6.2/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx.rb:12:in `require'
/home/sula/.rvm/gems/ruby-2.6.2/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx.rb:12:in `<top (required)>'
/home/sula/.rvm/gems/ruby-2.6.2/gems/thinking-sphinx-3.3.0/lib/thinking-sphinx.rb:1:in `require'
/home/sula/.rvm/gems/ruby-2.6.2/gems/thinking-sphinx-3.3.0/lib/thinking-sphinx.rb:1:in `<top (required)>'
/home/sula/my_work/storage marketplace/sharetribe/config/application.rb:22:in `<top (required)>'
/home/sula/my_work/storage marketplace/sharetribe/Rakefile:4:in `require'
/home/sula/my_work/storage marketplace/sharetribe/Rakefile:4:in `<top (required)>'
/home/sula/.rvm/gems/ruby-2.6.2/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/sula/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks:24:in `eval'
/home/sula/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks:24:in `<main>'
`

##### Additional information

_Please provide any additional information that helps debugging, e.g. log output or stack trace of the error_

**Comment by Sultan91** [comment]
Cured by :by putting flag `-T`: 
 `bundle exec rake -T db:create db:structure:load`
