### ISSUE TITLE
Zeus - cucumber and test fail to launch

### ISSUE THREAD

**Issue by mierz00** [sharetribe/sharetribe#3839]
Cucumber and test failing to launch when running ```zeus start```

##### Sharetribe Version:

Last commit from Sharetribe was: 
ee9d94ff14dddda998989b6367b160dc63e858fc

##### Environment:
```
Mac OS X 10.14.6 Mojave
```
_What's your node version? Run the following commands and copy the result here:_

```
v7.8.0
```

##### Server mode:

```
Development
```

##### Description:

Receiving errors when attempting to run ```zeus start```.  Sharetribe is definitely working as I've been able to use the platform without running the tests.

I was having difficulties running zeus on Mac. Eventually I was able to run zeus using the latest version: ```0.15.15.pre```. Now when running ```zeus start``` I'm seeing these errors. 

I believe it has to do with the fact that I'm not using the recommended version of zeus. If anyone has any ideas on how to fix this problem that would be great. 

![Screen Shot 2019-08-16 at 12 45 00 pm](https://user-images.githubusercontent.com/24411259/63162983-504ba080-c024-11e9-97e0-e191fe304601.png)

Cucumber and test backtraces are both the exact same:
```
zeus cucumber
/Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeus-0.15.15.pre/lib/zeus/load_tracking.rb:62:in `write': Bad file descriptor (Errno::EBADF)
	from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeus-0.15.15.pre/lib/zeus/load_tracking.rb:62:in `puts'
	from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeus-0.15.15.pre/lib/zeus/load_tracking.rb:62:in `block (2 levels) in notify_features'
	from /Users/user/.rbenv/versions/2.6.3/lib/ruby/2.6.0/set.rb:338:in `each_key'
	from /Users/user/.rbenv/versions/2.6.3/lib/ruby/2.6.0/set.rb:338:in `each'
	from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeus-0.15.15.pre/lib/zeus/load_tracking.rb:61:in `block in notify_features'
	from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeus-0.15.15.pre/lib/zeus/load_tracking.rb:60:in `synchronize'
	from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeus-0.15.15.pre/lib/zeus/load_tracking.rb:60:in `notify_features'
	from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeus-0.15.15.pre/lib/zeus/load_tracking.rb:36:in `ensure in track_features_loaded_by'
	from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeus-0.15.15.pre/lib/zeus/load_tracking.rb:36:in `track_features_loaded_by'
	from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeus-0.15.15.pre/lib/zeus.rb:202:in `run_action'
	from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeus-0.15.15.pre/lib/zeus.rb:75:in `block in boot_steps'
	from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeus-0.15.15.pre/lib/zeus.rb:57:in `catch'
	from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeus-0.15.15.pre/lib/zeus.rb:57:in `boot_steps'
	from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zeus-0.15.15.pre/lib/zeus.rb:49:in `go'
	from -e:1:in `<main>'
```
##### Steps To Reproduce:

1. Clone Sharetribe to mac.
2. Complete all the installation instructions. 
3. Upgrade zeus to version 0.15.15.pre.
4. run ```zeus start``` 
5. Run ``` zeus cucumber``` or ```zeus test``` in another terminal window.

**Comment by thomasmalbaux** [comment]
Thanks for reporting. That sounds quite specific indeed, as it uses a different version and is hard to reproduce.

I'm a bit confused: why did you decide to use that version of zeus, instead of the recommended one?

**Comment by mierz00** [comment]
Hi @thomasmalbaux, thanks for getting back to me. 

The original reason was that zeus start kept crashing. Upon reading issues in the zeus repo it was recommended to upgrade versions. I've now downgraded back to the Sharetribe version ```0.15.13``` and I'm still seeing similar issues. 

If I try to run zeus start I get this: 
![Screen Shot 2019-08-17 at 10 33 10 pm](https://user-images.githubusercontent.com/24411259/63217021-07d4d580-c13f-11e9-8561-b5001d59f13e.png)

If I try to get any of the backtraces I get this: 
![Screen Shot 2019-08-17 at 10 34 34 pm](https://user-images.githubusercontent.com/24411259/63217033-3fdc1880-c13f-11e9-8c6f-0ad89f5949c4.png)

Now, I tried following the advice given [here](https://github.com/burke/zeus/issues/641#issuecomment-408753975) which gets zeus running, but I get the same errors outlined in my original post. 

![Screen Shot 2019-08-17 at 10 39 02 pm](https://user-images.githubusercontent.com/24411259/63217080-d7416b80-c13f-11e9-86fb-371177bd0458.png)

And the exact same backtrace errors. 

I've tried to locate where the errors are coming from but no luck so far. I've commented out the the function calls to `DatabaseCleaner.clean_with(:truncation)` , `TestHelpers` and `ThinkingSphinx` within `custom_plan.rb` which makes zeus happy but obviously those function calls are all required.

Have you guys had any success in running the tests on mac? Or do you know of any way I can debug where exactly it's failing?

**Comment by MrHakala** [comment]
I'm currently running tests on mac. Have you tried logging?
`zeus --log ZEUS.LOG start`

**Comment by mierz00** [comment]
Hi @MrHakala, 

Yes, I have. Here are the results: 
```
2019/08/23 13:44:28.017891 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:142] test_helper/(no PID) entering state SUnbooted
2019/08/23 13:44:28.017961 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:142] test_environment/(no PID) entering state SUnbooted
2019/08/23 13:44:28.017995 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:142] cucumber_environment/(no PID) entering state SUnbooted
2019/08/23 13:44:28.018004 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:142] development_environment/(no PID) entering state SUnbooted
2019/08/23 13:44:28.018027 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:142] prerake/(no PID) entering state SUnbooted
2019/08/23 13:44:28.018066 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:142] default_bundle/(no PID) entering state SUnbooted
2019/08/23 13:44:28.018163 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:142] boot/(no PID) entering state SUnbooted
2019/08/23 13:44:28.018375 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:380] boot/(no PID) running the root command now
2019/08/23 13:44:28.289661 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:128] boot/(3805) initialized slave boot with pid 3805 from parent 0
2019/08/23 13:44:28.289718 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:145] boot/(3805) entering state SBooting
2019/08/23 13:44:31.358303 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:220] boot/(3805) received action message
2019/08/23 13:44:31.358348 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:148] boot/(3805) entering state SReady
2019/08/23 13:44:31.358373 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:328] boot/(3805) now sending slave boot request for default_bundle
2019/08/23 13:44:31.362078 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:128] default_bundle/(3806) initialized slave default_bundle with pid 3806 from parent 3805
2019/08/23 13:44:31.362130 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:145] default_bundle/(3806) entering state SBooting
2019/08/23 13:44:35.980805 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:220] default_bundle/(3806) received action message
2019/08/23 13:44:35.980866 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:148] default_bundle/(3806) entering state SReady
2019/08/23 13:44:35.980882 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:328] default_bundle/(3806) now sending slave boot request for test_environment
2019/08/23 13:44:35.980909 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:328] default_bundle/(3806) now sending slave boot request for development_environment
2019/08/23 13:44:35.983827 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:128] test_environment/(3813) initialized slave test_environment with pid 3813 from parent 3806
2019/08/23 13:44:35.983876 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:145] test_environment/(3813) entering state SBooting
2019/08/23 13:44:35.984430 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:128] development_environment/(3814) initialized slave development_environment with pid 3814 from parent 3806
2019/08/23 13:44:35.984479 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:145] development_environment/(3814) entering state SBooting
2019/08/23 13:44:37.964266 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:220] development_environment/(3814) received action message
2019/08/23 13:44:37.964316 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:148] development_environment/(3814) entering state SReady
2019/08/23 13:44:37.964357 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:328] development_environment/(3814) now sending slave boot request for prerake
2019/08/23 13:44:37.968412 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:128] prerake/(3816) initialized slave prerake with pid 3816 from parent 3814
2019/08/23 13:44:37.968453 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:145] prerake/(3816) entering state SBooting
2019/08/23 13:44:38.016835 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:220] prerake/(3816) received action message
2019/08/23 13:44:38.016885 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:148] prerake/(3816) entering state SReady
2019/08/23 13:44:39.609857 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:220] test_environment/(3813) received action message
2019/08/23 13:44:39.609895 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:148] test_environment/(3813) entering state SReady
2019/08/23 13:44:39.609909 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:328] test_environment/(3813) now sending slave boot request for test_helper
2019/08/23 13:44:39.609932 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:328] test_environment/(3813) now sending slave boot request for cucumber_environment
2019/08/23 13:44:39.613368 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:128] test_helper/(3835) initialized slave test_helper with pid 3835 from parent 3813
2019/08/23 13:44:39.613419 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:145] test_helper/(3835) entering state SBooting
2019/08/23 13:44:39.613839 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:128] cucumber_environment/(3836) initialized slave cucumber_environment with pid 3836 from parent 3813
2019/08/23 13:44:39.613873 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:145] cucumber_environment/(3836) entering state SBooting
2019/08/23 13:44:44.706138 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:220] cucumber_environment/(3836) received action message
2019/08/23 13:44:44.706391 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:151] cucumber_environment/(no PID) entering state SCrashed
2019/08/23 13:44:48.971480 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:220] test_helper/(3835) received action message
2019/08/23 13:44:48.971565 [/Users/phil/Source/go/src/github.com/burke/zeus/go/processtree/slavenode.go:151] test_helper/(no PID) entering state SCrashed
```

I've tried to have a look for the SCrashed errors but I couldn't find anything to solve the issue.

**Comment by mierz00** [comment]
I've managed to figure it out. For anyone that has similar issues, make sure you run both `bundle exec rspec` and `bundle exec cucumber` to see if there are any errors. 

In my case, I had errors in tests I created and for cucumber I didn't have PhantomJS installed using homebrew.
